# Generated by Django 3.2.11 on 2022-01-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField(verbose_name='Conteudo')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('sub_title', models.CharField(max_length=200, verbose_name='Sub titulo')),
                ('content', models.TextField(verbose_name='Conteudo')),
                ('category', models.CharField(choices=[('TC', 'Tecnologia'), ('CR', 'Curiosidades'), ('GR', 'Geral')], default='GR', max_length=2, verbose_name='Categorias')),
                ('approved', models.BooleanField(default=True, verbose_name='Aprovado')),
                ('image_post', models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Imagem')),
            ],
        ),
    ]
