# Generated by Django 3.2.11 on 2022-01-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub_title',
            field=models.CharField(max_length=200, verbose_name='Sub titulo'),
        ),
    ]
