# Generated by Django 3.2.11 on 2022-01-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_post_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
    ]
