# Generated by Django 3.2.11 on 2022-01-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=True, verbose_name='Aprovado'),
        ),
    ]
