# Generated by Django 3.2.11 on 2022-01-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_post_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categorie',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TC', 'Tecnologia'), ('CR', 'Curiosidades'), ('GR', 'Geral')], default='GR', max_length=2, verbose_name='Categorias'),
        ),
    ]
