# Generated by Django 3.2.11 on 2022-01-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20220106_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
