# Generated by Django 3.2.11 on 2022-01-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_post_image_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField(verbose_name='Conteudo')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Conteudo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
    ]
